-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Observation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "incidentId" TEXT NOT NULL,
    "deploymentId" TEXT NOT NULL,
    "recordedAtUtc" DATETIME NOT NULL,
    "source" TEXT NOT NULL,
    "hrBpm" REAL,
    "spo2Pct" REAL,
    "coreTempC" REAL,
    "respRatePerMin" REAL,
    "fatiguePct" REAL,
    "hydrationPct" REAL,
    "fallDetected" BOOLEAN NOT NULL DEFAULT false,
    "hrUpdatedAtUtc" DATETIME,
    "spo2UpdatedAtUtc" DATETIME,
    "coreTempUpdatedAtUtc" DATETIME,
    "respRateUpdatedAtUtc" DATETIME,
    "fatigueUpdatedAtUtc" DATETIME,
    "hydrationUpdatedAtUtc" DATETIME,
    "ambientTempC" REAL,
    "humidityPct" REAL,
    "coPpm" REAL,
    "pm25UgM3" REAL,
    "windSpeedMs" REAL,
    "windDirDeg" REAL,
    "ambientTempUpdatedAtUtc" DATETIME,
    "humidityUpdatedAtUtc" DATETIME,
    "coUpdatedAtUtc" DATETIME,
    "pm25UpdatedAtUtc" DATETIME,
    "windSpeedUpdatedAtUtc" DATETIME,
    "windDirUpdatedAtUtc" DATETIME,
    "lat" REAL NOT NULL,
    "lng" REAL NOT NULL,
    "distanceToFireFrontM" REAL,
    "distanceToSafeZoneM" REAL,
    "escapeRouteStatus" TEXT NOT NULL,
    "scbaPressurePct" REAL,
    "scbaOnAir" BOOLEAN NOT NULL DEFAULT true,
    "timeOnTaskMin" REAL NOT NULL,
    "manualMaydayActive" BOOLEAN NOT NULL DEFAULT false,
    "positionFixUpdatedAtUtc" DATETIME,
    "distanceToFireFrontUpdatedAtUtc" DATETIME,
    "distanceToSafeZoneUpdatedAtUtc" DATETIME,
    "escapeRouteUpdatedAtUtc" DATETIME,
    "scbaPressureUpdatedAtUtc" DATETIME,
    "wearingPpe" BOOLEAN NOT NULL DEFAULT true,
    "derivedCoreTempC" REAL,
    "derivedCoreTempUpdatedAtUtc" DATETIME,
    "derivedFatiguePct" REAL,
    "derivedFatigueUpdatedAtUtc" DATETIME,
    "derivedHrrFraction" REAL,
    "derivedEffectiveHrReserveBpm" REAL,
    "derivedMetabolicRateWm2" REAL,
    "derivedHeatStorageWm2" REAL,
    "derivedSweatRateGPerHour" REAL,
    "derivedDlimMin" REAL,
    "derivedHeatStrainLimiter" TEXT,
    "derivedCoreTempLimitC" REAL,
    "derivedCohbPct" REAL,
    "derivedCoIndex" REAL,
    "derivedPm25DoseUgMinM3" REAL,
    "derivedPm25Index" REAL,
    "derivedStepMinutes" REAL,
    "derivedStepCapped" BOOLEAN,
    "physiologyCaveatsJson" TEXT,
    "physiologyModelVersion" TEXT,
    "physiologyConfigHash" TEXT,
    "fireProviderKey" TEXT,
    "fireFrontConfidence" TEXT,
    CONSTRAINT "Observation_incidentId_fkey" FOREIGN KEY ("incidentId") REFERENCES "Incident" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Observation_deploymentId_fkey" FOREIGN KEY ("deploymentId") REFERENCES "Deployment" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_Observation" ("ambientTempC", "ambientTempUpdatedAtUtc", "coPpm", "coUpdatedAtUtc", "coreTempC", "coreTempUpdatedAtUtc", "deploymentId", "distanceToFireFrontM", "distanceToFireFrontUpdatedAtUtc", "distanceToSafeZoneM", "distanceToSafeZoneUpdatedAtUtc", "escapeRouteStatus", "escapeRouteUpdatedAtUtc", "fallDetected", "fatiguePct", "fatigueUpdatedAtUtc", "fireFrontConfidence", "fireProviderKey", "hrBpm", "hrUpdatedAtUtc", "humidityPct", "humidityUpdatedAtUtc", "hydrationPct", "hydrationUpdatedAtUtc", "id", "incidentId", "lat", "lng", "manualMaydayActive", "pm25UgM3", "pm25UpdatedAtUtc", "positionFixUpdatedAtUtc", "recordedAtUtc", "respRatePerMin", "respRateUpdatedAtUtc", "scbaOnAir", "scbaPressurePct", "scbaPressureUpdatedAtUtc", "source", "spo2Pct", "spo2UpdatedAtUtc", "timeOnTaskMin", "windDirDeg", "windDirUpdatedAtUtc", "windSpeedMs", "windSpeedUpdatedAtUtc") SELECT "ambientTempC", "ambientTempUpdatedAtUtc", "coPpm", "coUpdatedAtUtc", "coreTempC", "coreTempUpdatedAtUtc", "deploymentId", "distanceToFireFrontM", "distanceToFireFrontUpdatedAtUtc", "distanceToSafeZoneM", "distanceToSafeZoneUpdatedAtUtc", "escapeRouteStatus", "escapeRouteUpdatedAtUtc", "fallDetected", "fatiguePct", "fatigueUpdatedAtUtc", "fireFrontConfidence", "fireProviderKey", "hrBpm", "hrUpdatedAtUtc", "humidityPct", "humidityUpdatedAtUtc", "hydrationPct", "hydrationUpdatedAtUtc", "id", "incidentId", "lat", "lng", "manualMaydayActive", "pm25UgM3", "pm25UpdatedAtUtc", "positionFixUpdatedAtUtc", "recordedAtUtc", "respRatePerMin", "respRateUpdatedAtUtc", "scbaOnAir", "scbaPressurePct", "scbaPressureUpdatedAtUtc", "source", "spo2Pct", "spo2UpdatedAtUtc", "timeOnTaskMin", "windDirDeg", "windDirUpdatedAtUtc", "windSpeedMs", "windSpeedUpdatedAtUtc" FROM "Observation";
DROP TABLE "Observation";
ALTER TABLE "new_Observation" RENAME TO "Observation";
CREATE INDEX "Observation_incidentId_recordedAtUtc_idx" ON "Observation"("incidentId", "recordedAtUtc");
CREATE INDEX "Observation_deploymentId_recordedAtUtc_idx" ON "Observation"("deploymentId", "recordedAtUtc");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
