/**
 * GeometricSpreadProvider — DEMO PLACEHOLDER ONLY.
 *
 * A wind-driven ellipse that grows with elapsed time. It is a drawing, not a
 * fire behaviour model. It contains no fuel model, no terrain, no moisture, no
 * atmospheric coupling and no validation of any kind.
 *
 * `isFireBehaviourPrediction` is hard-coded false and cannot be overridden.
 * Anything reading a front from this provider must present it as a placeholder.
 *
 * Real fire spread prediction is FARSITE / Phoenix RapidFire / observed
 * satellite perimeters. Valoris consumes those; it does not compete with them.
 */

import { offsetMetres } from "./geometry";
import {
  type FireFront,
  type FireFrontProvider,
  type FireFrontProviderKey,
  type FireFrontQuery,
} from "./types";

export type GeometricSpreadConfig = {
  /** Radius of the ellipse across the wind at t=0. */
  initialRadiusM: number;
  /** Downwind growth rate. Purely illustrative. */
  headSpreadMPerMin: number;
  /** Upwind growth rate. */
  backSpreadMPerMin: number;
  /** Across-wind growth rate. */
  flankSpreadMPerMin: number;
  /** Vertices in the generated ring. */
  vertexCount: number;
};

export const DEFAULT_GEOMETRIC_SPREAD_CONFIG: GeometricSpreadConfig = {
  initialRadiusM: 120,
  headSpreadMPerMin: 14,
  backSpreadMPerMin: 3,
  flankSpreadMPerMin: 6,
  vertexCount: 48,
};

/** Wind speed above which the head/flank ratio stops increasing. */
const WIND_SATURATION_MS = 15;
/** Multiplier applied to head spread at saturating wind. */
const MAX_WIND_GAIN = 2.5;
const MS_PER_MIN = 60_000;

export class GeometricSpreadProvider implements FireFrontProvider {
  readonly key: FireFrontProviderKey = "geometric_spread_placeholder";
  readonly label = "Geometric spread (placeholder — not a fire behaviour model)";

  private readonly config: GeometricSpreadConfig;

  constructor(config: GeometricSpreadConfig = DEFAULT_GEOMETRIC_SPREAD_CONFIG) {
    this.config = config;
  }

  isAvailable(): boolean {
    return true;
  }

  unavailableReason(): string {
    return "";
  }

  async getFireFront(query: FireFrontQuery): Promise<FireFront> {
    return this.getFireFrontSync(query);
  }

  /** Deterministic and synchronous — the async method just wraps this. */
  getFireFrontSync(query: FireFrontQuery): FireFront {
    const { initialRadiusM, headSpreadMPerMin, backSpreadMPerMin, flankSpreadMPerMin, vertexCount } =
      this.config;

    const elapsedMin = Math.max(0, query.elapsedMs) / MS_PER_MIN;
    const windSpeedMs = Math.max(0, query.windSpeedMs ?? 0);
    const windGain =
      1 +
      (MAX_WIND_GAIN - 1) * Math.min(1, windSpeedMs / WIND_SATURATION_MS);

    // Wind direction is the direction the wind comes FROM, so the fire head
    // runs 180 degrees from it.
    const windFromDeg = query.windDirDeg ?? 0;
    const headBearingDeg = (windFromDeg + 180) % 360;
    const headBearingRad = (headBearingDeg * Math.PI) / 180;

    const headM = initialRadiusM + headSpreadMPerMin * windGain * elapsedMin;
    const backM = initialRadiusM + backSpreadMPerMin * elapsedMin;
    const flankM = initialRadiusM + flankSpreadMPerMin * elapsedMin;

    // Ellipse centred between the head and back extents, along the head bearing.
    const centreOffsetM = (headM - backM) / 2;
    const semiMajorM = (headM + backM) / 2;
    const semiMinorM = flankM;

    const perimeter = [];
    for (let i = 0; i < vertexCount; i += 1) {
      const t = (2 * Math.PI * i) / vertexCount;
      // Local ellipse coords: u along the head bearing, v across it.
      const u = centreOffsetM + semiMajorM * Math.cos(t);
      const v = semiMinorM * Math.sin(t);
      // Rotate (u, v) so u points along the head bearing (bearing is clockwise
      // from north, so north = cos, east = sin).
      const northM = u * Math.cos(headBearingRad) - v * Math.sin(headBearingRad);
      const eastM = u * Math.sin(headBearingRad) + v * Math.cos(headBearingRad);
      perimeter.push(offsetMetres(query.origin, eastM, northM));
    }

    return {
      providerKey: this.key,
      providerLabel: this.label,
      validAtMs: query.atMs,
      perimeter,
      // Never better than "low": this is a shape, not an observation.
      confidence: "low",
      isFireBehaviourPrediction: false,
      provenance:
        "Placeholder wind-driven ellipse generated by Valoris for demonstration. " +
        "Not a fire behaviour prediction. No fuel model, terrain, moisture or " +
        "validation. Do not interpret as a forecast of real fire spread.",
      isProjection: query.atMs > query.nowMs,
    };
  }
}
